apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: d9axm6i9a-nodejs 
  janus-idp.io/tekton: d9axm6i9a-nodejs
  backstage.io/kubernetes-id: d9axm6i9a-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d9axm6i9a-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml