apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d9axm6i9a-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d9axm6i9a-nodejs 
  name: d9axm6i9a-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: d9axm6i9a-nodejs 
